import { assertNoHorizontalOverflow } from './responsive_assertions.mjs';
import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
const browser=await chromium.launch({headless:true});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000}}), errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(resolve('frontend/index.html')).href);await page.locator('#case-summary h2').waitFor();
 const raw={name:'operating-test',bus:Object.fromEntries(Array.from({length:600},(_,i)=>['b'+i,{terminal_names:['a','n'],longitude:-2.6,latitude:53.48}]))};
 raw.line={l:{bus_from:'b0',bus_to:'b1',terminal_map_from:['a','n'],terminal_map_to:['a','n'],i_max:[100,50]}};
 async function upload(selector,name,data){await page.locator(selector).setInputFiles({name,mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await page.locator('#import-progress').waitFor({state:'detached'});}
 await upload('#file-input','region.json',raw);await page.locator('[data-view="geo"]').click();
 await page.locator('#region-operating-layer').selectOption('voltage');
 assert.match(await page.locator('#region-operating-legend').innerText(),/0\/600 elements have values/);
 const results={objective:0,bus:{b0:{vm:[230,0]},b1:{vm:[null,0]},b2:{vm:[false,null]}},line:{l:{a:{cm_fr:100,cm_to:120},n:{cm_fr:0,cm_to:0}}}};
 await upload('#result-input','results.json',results);
 assert.match(await page.locator('#region-operating-legend').innerText(),/2\/600 elements have values · 1 complete · 1 partial/);
 await page.locator('#region-operating-show').click();
 assert.equal(await page.locator('[data-operating-row]').count(),50);
 assert.match(await page.locator('#region-operating-evidence').innerText(),/Terminal n; reference not declared/);
 await page.locator('[data-operating-next]').click();assert.match(await page.locator('#region-operating-evidence').innerText(),/Page 2/);
 const scale=await page.locator('.operating-scale').innerText();
 await page.locator('[data-region-cell]').first().press('Enter');
 assert.equal(await page.locator('.operating-scale').innerText(),scale);
 assert.match(await page.locator('#region-operating-evidence').innerText(),/selected group/);
 await page.locator('#region-operating-layer').selectOption('loading');
 assert.match(await page.locator('#region-operating-legend').innerText(),/1\/1 elements have values · 1 complete/);
 assert.match(await page.locator('#region-map [data-region-cell] title').first().textContent(),/Maximum 1.2; 1\/1/);
 assert.match(await page.locator('#region-operating-evidence').innerText(),/120 A ÷ 100 A/);
 await page.locator('#region-operating-layer').selectOption('deviation');
 assert.match(await page.locator('#region-operating-legend').innerText(),/0\/600/);
 results.bus.b0.voltage_deviation=.08;results.bus.b0.voltage_reference='nominal phase-to-ground 230 V';
 results.meta={case_id:'wrong-case'};
 await upload('#result-input','mismatch.json',results);
 assert.match(await page.locator('#region-operating-legend').innerText(),/suppressed because case identity mismatches/);
 assert.equal(await page.locator('[data-region-cell] circle').first().getAttribute('fill'),'url(#operating-missing)');
 delete results.meta;
 await upload('#result-input','results.json',results);
 await page.locator('#region-operating-layer').selectOption('voltage');
 await page.locator('[data-operating-close]').click();
 await page.screenshot({path:'/tmp/operating-layers.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await assertNoHorizontalOverflow(page);
 await upload('#result-input','scenarios.json',{objective:0,nw:{day:results,night:{bus:{b0:{vm:[220,0]}}}}});
 assert.match(await page.locator('#region-operating-legend').innerText(),/Choose a scenario/);
 assert.match(await page.locator('#region-operating-legend').innerText(),/0\/600/);
 await page.locator('#region-scenario').selectOption('day');
 assert.match(await page.locator('#region-operating-legend').innerText(),/2\/600/);
 await page.locator('#region-scenario').selectOption('night');
 assert.match(await page.locator('#region-operating-legend').innerText(),/1\/600/);
 const complexResults={objective:0,bus:{b0:{a:{vm:230,vr:230,vi:0},n:{vm:5,vr:3,vi:4}},b1:{a:{vm:210,vr:210,vi:0},n:{vm:0,vr:0,vi:0}}}};
 await upload('#result-input','complex.json',complexResults);
 await page.locator('#region-voltage-terminal').selectOption(JSON.stringify('n'));
 await page.locator('#region-operating-show').click();
 assert.match(await page.locator('#region-operating-evidence').innerText(),/5.000–5.000 V/);
 await page.locator('#region-voltage-terminal').selectOption('null');
 await page.locator('#region-voltage-reference').selectOption(JSON.stringify('n'));
 assert.match(await page.locator('#region-operating-evidence').innerText(),/Selected reference n: 5 V/);
 assert.match(await page.locator('#region-operating-evidence').innerText(),/magnitude of complex difference/);
 assert.match(await page.locator('#region-map [data-region-cell] title').first().textContent(),/Minimum 210/);
 await page.setViewportSize({width:1440,height:1000});
 await page.locator('#region-voltage-controls').scrollIntoViewIfNeeded();
 await page.screenshot({path:'/tmp/conductor-voltage.png'});
 await page.locator('#region-voltage-reference').selectOption('null');
 const fixture=JSON.parse(await readFile('fixtures/micro/micro_bmopf.json','utf8'));
 Object.values(fixture.bus).forEach((bus,i)=>{bus.longitude=-2.6+i*.001;bus.latitude=53.48;});
 await upload('#file-input','micro.json',fixture);
 await upload('#result-input','micro-results.json',JSON.parse(await readFile('fixtures/micro/micro_bmopf_result.json','utf8')));
 await page.locator('#region-operating-layer').selectOption('voltage');
 assert.match(await page.locator('#region-operating-legend').innerText(),/3\/4 elements have values/);
 await page.locator('#region-operating-show').click();
 assert.match(await page.locator('#region-operating-evidence').innerText(),/Voltage array cannot be aligned/);
 await page.locator('#region-operating-layer').selectOption('loading');
 await page.locator('#region-operating-show').click();
 assert.match(await page.locator('#region-operating-evidence').innerText(),/0.6100 p.u./);
 assert.deepEqual(errors,[]);
} finally {await browser.close();}
