import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {chromium} from 'playwright';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {assertNoHorizontalOverflow} from './responsive_assertions.mjs';
const browser=await chromium.launch({headless:true});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(resolve('frontend/index.html')).href);await page.locator('#case-summary h2').waitFor();
 await page.evaluate(()=>{globalThis.__BMOPF_CASE__={name:'old embedded case'};globalThis.__BMOPF_REPORT_META__={case_fingerprint:'stale-fingerprint'};});
 async function upload(selector,name,data){await page.locator(selector).setInputFiles({name,mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await page.locator('#import-progress').waitFor({state:'detached'});}
 const raw={name:'Review <test>',bus:{a:{terminal_names:['p'],v_min:[220],v_max:[240],longitude:-2.6,latitude:53.48},b:{terminal_names:['p'],longitude:-2.61,latitude:53.49}},line:{l:{bus_from:'a',bus_to:'b',terminal_map_from:['p'],terminal_map_to:['p']}}};
 await upload('#file-input','review.json',raw);
 const line=()=>page.locator('#canvas path[data-kind="line"][data-id="l"]').first();
 const neutralColour=await line().getAttribute('stroke');
 const result={objective:0,meta:{case_fingerprint:'new-fingerprint'},bus:{a:{vm:[1.1]},b:{vm:[1.2]}},line:{l:{loading:null}}};
 await upload('#result-input','review-results.json',result);
 assert.equal(await line().getAttribute('stroke'),neutralColour);
 assert.doesNotMatch(await page.locator('#class-overview').innerText(),/loading 0(?:\s|·)/);
 assert.doesNotMatch(await page.locator('#canvas g[data-kind="bus"][data-id="a"] title').textContent(),/voltage deviation=/);
 result.line.l.loading=1.5;await upload('#result-input','review-results.json',result);
 assert.equal(await line().getAttribute('stroke'),'#ca6747');
 await page.locator('[data-view="geo"]').click();await page.locator('#region-question').selectOption('loading');
 assert.equal(await page.locator('#region-map polyline[data-id="l"]').getAttribute('stroke'),'#ca6747');
 assert.equal(await page.locator('.operating-scale i').count(),5);
 assert.equal(await page.locator('#region-map').evaluate(el=>el.getBoundingClientRect().top<650),true);
 await upload('#file-input','review.json',raw);
 assert.match(await page.locator('#region-issue-summary').innerText(),/assessment not run/);
 assert.equal(await page.locator('[data-summary-category="violation"]').count(),0);
 assert.doesNotMatch(await page.locator('#region-issue-summary').innerText(),/Unassessable checks/);
 const solved={objective:0,bus:{a:{p:{vm:250}},b:{p:{vm:230}}},line:{l:{loading:1.5}}};
 await upload('#result-input','scenarios.json',{objective:0,nw:{day:solved,night:solved}});
 assert.match(await page.locator('#region-issue-summary').innerText(),/select a scenario/);
 await page.locator('#region-scenario').selectOption('day');
 assert.match(await page.locator('#region-issue-summary').innerText(),/Violated checks: 1/);
 assert.match(await page.locator('#region-issue-summary').innerText(),/Passed checks: 1/);
 await page.locator('#region-question').selectOption('limits');
 assert.equal(await page.locator('#region-drawer').isVisible(),true);
 const positions=await page.evaluate(()=>({map:document.getElementById('region-map').getBoundingClientRect().right,drawer:document.getElementById('region-drawer').getBoundingClientRect().left}));
 assert.ok(positions.map<=positions.drawer+1);
 await page.locator('[data-issue-pin]').first().click();await page.locator('#region-review-open').click();
 assert.match(await page.locator('#region-review').innerText(),/1 pinned findings/);
 const reviewDownload=page.waitForEvent('download');await page.locator('#region-review-export').click();
 const review=JSON.parse(await readFile(await (await reviewDownload).path(),'utf8'));
 assert.equal(review.findings[0].context.scenario,'day');assert.equal(review.findings[0].value,250);assert.equal(review.findings[0].limit,240);
 await page.locator('#region-drawer-close').click();await page.locator('#region-question').selectOption('voltage');
 const svgDownload=page.waitForEvent('download');await page.locator('[data-camera="export-svg"]').click();
 const svgFile=await svgDownload;await svgFile.saveAs('/tmp/review-figure.svg');
 const svg=await readFile(await svgFile.path(),'utf8');
 assert.match(svg,/Review &lt;test&gt;/);assert.match(svg,/Scenario: day/);assert.match(svg,/unverified/);assert.match(svg,/Terminals: all declared/);assert.match(svg,/violated \/ 1 passed/);assert.match(svg,/<metadata>/);assert.match(svg,/pinned|Selection:/);
 await page.evaluate(svg=>{const parsed=new DOMParser().parseFromString(svg,'image/svg+xml');if(parsed.querySelector('parsererror'))throw Error('Invalid exported SVG');},svg);
 const pngDownload=page.waitForEvent('download');await page.locator('[data-camera="export-png"]').click();
 const pngFile=await pngDownload;await pngFile.saveAs('/tmp/review-figure.png');
 const png=await readFile(await pngFile.path());assert.equal(png.subarray(1,4).toString(),'PNG');assert.ok(png.readUInt32BE(20)>1000);
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'/tmp/review-workspace.png'});
 await page.setViewportSize({width:390,height:844});await assertNoHorizontalOverflow(page);
 assert.deepEqual(errors,[]);
}finally{await browser.close();}
